### ISSUE TITLE
Inference on custom dataset 

### ISSUE THREAD

**Issue by abhigoku10** [ayushais/DBLiDARNet#1]
@ayushais  hi thanks for sharing your work i had few quereis , 
1.can we use ur inference on custom data / nuscenes / lyft dataset 
2. whats the inference time your obtaining on ur system 
thanks in advance

**Comment by ayushais** [comment]
Hi, 
1. Yes you can use inference  some custom data, as long as the data is in the similar format i.e a an image with dimension 64X512x5. Please look into this paper for better information on this dataset https://arxiv.org/abs/1710.07368
2. I think it was around 47ms

**Comment by abhigoku10** [comment]
@ayushais how to obtain the custom dataset into the tf record format ?
