### ISSUE TITLE
Training on semantic Kitti 

### ISSUE THREAD

**Issue by abhigoku10** [ayushais/DBLiDARNet#2]
@ayushais  have you tried to run the network on semanttic kitti dataset ?? Or have you tried to train the network on objects like trees building poles ??

**Comment by ayushais** [comment]
I added the results to README.md , you can see at the bottom of the page here
https://github.com/ayushais/DBLiDARNet

**Comment by abhigoku10** [comment]
@ayushais  thanks for the response , 
from your inference code can we obtain the following 
1. location of the segmented objects i.e poles trees
2. draw bounding box around the segment objects 
thanks in advance

**Comment by ayushais** [comment]
@abhigoku10 
My inference only gives you the segmentation masks. To get the location and the boxes, you probably need to cluster (Euclidean) it to get separate instances of poles or trees. From each cluster you can then get the location and the bounding box.
